"""Dictionary chain registry.

Executes the user's per-language ordered chain of providers. The first
provider that returns a non-empty WordEntry wins. The chain is sourced from
the user's settings; if a provider is unknown or disabled, it's skipped.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Callable

from ...util import is_valid_lang
from .base import WordEntry  # noqa: F401

log = logging.getLogger(__name__)

PROVIDERS: dict[str, Callable[..., WordEntry]] = {}
PROVIDER_SUPPORTS: dict[str, Callable[[str], bool]] = {}


@dataclass
class ChainResult:
    """Outcome of running the chain. `entry` is the first non-empty result;
    `errors` lists every provider that raised (with the short error string
    coerced to str). The UI uses `errors` to distinguish 'word has no senses'
    from 'every provider failed'."""

    entry: WordEntry
    errors: list[dict] = field(default_factory=list)


def register(name: str, fn: Callable[..., WordEntry], *,
             supports: Callable[[str], bool] | None = None) -> None:
    PROVIDERS[name] = fn
    if supports is not None:
        PROVIDER_SUPPORTS[name] = supports


def supports_provider(name: str, lang: str) -> bool:
    """Whether the named provider can look up words in `lang`. Defaults to True
    if the provider didn't declare a `supports` predicate."""
    fn = PROVIDER_SUPPORTS.get(name)
    if fn is None:
        return True
    try:
        return bool(fn(lang))
    except Exception:  # noqa: BLE001
        return True


def available_providers() -> list[str]:
    """Every registered provider name, installed or not. The chain
    executor and the Settings UI both filter on top of this; this method
    is the unfiltered registry view."""
    return sorted(PROVIDERS.keys())


def installed_providers_for(lang: str) -> set[str]:
    """Subset of ``available_providers()`` that the user has actually
    installed for ``lang``. The LLM provider is always considered
    installed because it has no offline data to fetch."""
    from . import installer
    result = installer.installed_providers(lang)
    installed = result if isinstance(result, set) else set()
    installed.add("llm")
    return installed


# Built-in display metadata. Add new entries here when registering a new
# provider so the UI can render a human label + short blurb.
PROVIDER_META: dict[str, dict] = {
    "wordnet": {
        "display_name": "WordNet",
        "description": "English lexical database (offline).",
        "kind": "builtin",
    },
    "llm": {
        "display_name": "AI",
        "description": "Generated by the configured language model.",
        "kind": "ai",
    },
}


def provider_info(name: str) -> dict | None:
    """Return display metadata for a provider. Always carries `name` and
    `supports(lang)` is computed per-language on the caller side."""
    meta = PROVIDER_META.get(name)
    if meta is None:
        return None
    return {"name": name, **meta}


def available_providers_detailed() -> list[dict]:
    """All registered providers with display metadata."""
    out: list[dict] = []
    for n in available_providers():
        info = provider_info(n)
        if info is not None:
            out.append(info)
    return out


def get(name: str) -> Callable[..., WordEntry] | None:
    return PROVIDERS.get(name)


def _installed_for(lang: str) -> set[str]:
    """Set of provider names the user has installed for ``lang``. Lazily
    imported so the registry module doesn't pull the installer (and its
    DB-touching code) into import-time of every settings/blueprint path."""
    from . import installer
    result = installer.installed_providers(lang)
    if isinstance(result, set):
        return result
    return set()


def lookup_via_chain(word: str, lang: str, chain: list[dict], **kwargs) -> ChainResult:
    """Walk the chain in order; first non-empty result wins.

    Returns a `ChainResult` carrying the winning entry (possibly empty) plus
    a list of `{provider, error}` dicts for every provider that raised. The
    UI uses this to distinguish 'no provider had this word' from 'every
    provider failed' (typically a network / LLM outage).
    """
    if not is_valid_lang(lang):
        return ChainResult(entry=WordEntry.empty(word, lang))
    if not isinstance(chain, list):
        return ChainResult(entry=WordEntry.empty(word, lang))
    installed = _installed_for(lang)
    errors: list[dict] = []
    for entry in chain:
        if not isinstance(entry, dict):
            continue
        if not entry.get("enabled", True):
            continue
        name = entry.get("name")
        if not isinstance(name, str):
            continue
        fn = PROVIDERS.get(name)
        if fn is None:
            continue
        # The LLM provider is always available (it has no install row — it
        # talks to the configured remote endpoint). Offline dictionaries
        # must have an install row, otherwise the user hasn't downloaded
        # them yet and we'd return false negatives.
        if name != "llm" and name not in installed:
            continue
        try:
            result = fn(word, lang, **kwargs)
        except Exception as e:  # noqa: BLE001 - chain continues
            errors.append({"provider": name, "error": str(e)})
            log.warning("provider %s raised on %s/%s: %s", name, lang, word, e)
            continue
        if not result.is_empty:
            return ChainResult(entry=result, errors=errors)
    if errors:
        log.info("chain exhausted with errors for %s/%s: %s", lang, word,
                 "; ".join(f"{e['provider']}: {e['error']}" for e in errors))
    return ChainResult(entry=WordEntry.empty(word, lang), errors=errors)


def lookup_with_provider(word: str, lang: str, provider_name: str, **kwargs) -> ChainResult:
    """Force one provider (used by manual 'Look up with AI' button).

    Returns a `ChainResult` so the UI can surface the failure reason when the
    forced provider errors out (e.g. AI timeout).
    """
    fn = PROVIDERS.get(provider_name)
    if fn is None:
        return ChainResult(entry=WordEntry.empty(word, lang))
    if provider_name != "llm" and provider_name not in _installed_for(lang):
        return ChainResult(entry=WordEntry.empty(word, lang))
    try:
        entry = fn(word, lang, **kwargs)
    except Exception as e:  # noqa: BLE001
        log.warning("forced provider %s failed on %s/%s: %s", provider_name, lang, word, e)
        return ChainResult(
            entry=WordEntry.empty(word, lang),
            errors=[{"provider": provider_name, "error": str(e)}],
        )
    return ChainResult(entry=entry)


def bootstrap() -> None:
    """Register built-in providers. Called once at app startup."""
    if PROVIDERS:
        return
    from . import llm as llm_provider
    from . import wordnet as wordnet_provider

    register("wordnet", wordnet_provider.lookup, supports=wordnet_provider.supports)
    register("llm", llm_provider.lookup, supports=llm_provider.supports)