"""Dictionary chain registry.

Executes the user's per-language ordered chain of providers. The first
provider that returns a non-empty WordEntry wins. The chain is sourced from
the user's settings; if a provider is unknown or disabled, it's skipped.
"""

from __future__ import annotations

import logging
from typing import Callable

from ...util import is_valid_lang
from .base import WordEntry  # noqa: F401

log = logging.getLogger(__name__)

PROVIDERS: dict[str, Callable[..., WordEntry]] = {}
PROVIDER_SUPPORTS: dict[str, Callable[[str], bool]] = {}


def register(name: str, fn: Callable[..., WordEntry], *,
             supports: Callable[[str], bool] | None = None) -> None:
    PROVIDERS[name] = fn
    if supports is not None:
        PROVIDER_SUPPORTS[name] = supports


def supports_provider(name: str, lang: str) -> bool:
    """Whether the named provider can look up words in `lang`. Defaults to True
    if the provider didn't declare a `supports` predicate."""
    fn = PROVIDER_SUPPORTS.get(name)
    if fn is None:
        return True
    try:
        return bool(fn(lang))
    except Exception:  # noqa: BLE001
        return True


def available_providers() -> list[str]:
    return sorted(PROVIDERS.keys())


# Built-in display metadata. Add new entries here when registering a new
# provider so the UI can render a human label + short blurb.
PROVIDER_META: dict[str, dict] = {
    "wordnet": {
        "display_name": "WordNet",
        "description": "English lexical database (offline).",
        "kind": "builtin",
    },
    "llm": {
        "display_name": "AI",
        "description": "Generated by the configured language model.",
        "kind": "ai",
    },
}


def provider_info(name: str) -> dict | None:
    """Return display metadata for a provider. Always carries `name` and
    `supports(lang)` is computed per-language on the caller side."""
    meta = PROVIDER_META.get(name)
    if meta is None:
        return None
    return {"name": name, **meta}


def available_providers_detailed() -> list[dict]:
    """All registered providers with display metadata."""
    out: list[dict] = []
    for n in available_providers():
        info = provider_info(n)
        if info is not None:
            out.append(info)
    return out


def get(name: str) -> Callable[..., WordEntry] | None:
    return PROVIDERS.get(name)


def lookup_via_chain(word: str, lang: str, chain: list[dict], **kwargs) -> WordEntry:
    """Walk the chain in order; first non-empty result wins.

    Empty chain or all providers empty => returns empty WordEntry (not an error).
    Provider raises => logged, skip, continue.
    """
    if not is_valid_lang(lang):
        return WordEntry.empty(word, lang)
    if not isinstance(chain, list):
        return WordEntry.empty(word, lang)
    last_error: str | None = None
    for entry in chain:
        if not isinstance(entry, dict):
            continue
        if not entry.get("enabled", True):
            continue
        name = entry.get("name")
        if not isinstance(name, str):
            continue
        fn = PROVIDERS.get(name)
        if fn is None:
            continue
        try:
            result = fn(word, lang, **kwargs)
        except Exception as e:  # noqa: BLE001 - chain continues
            last_error = f"{name}: {e}"
            log.warning("provider %s raised on %s/%s: %s", name, lang, word, e)
            continue
        if not result.is_empty:
            return result
    if last_error:
        log.info("chain exhausted with errors for %s/%s: %s", lang, word, last_error)
    return WordEntry.empty(word, lang)


def lookup_with_provider(word: str, lang: str, provider_name: str, **kwargs) -> WordEntry:
    """Force one provider (used by manual 'Look up with AI' button)."""
    fn = PROVIDERS.get(provider_name)
    if fn is None:
        return WordEntry.empty(word, lang)
    try:
        return fn(word, lang, **kwargs)
    except Exception as e:  # noqa: BLE001
        log.warning("forced provider %s failed on %s/%s: %s", provider_name, lang, word, e)
        return WordEntry.empty(word, lang)


def bootstrap() -> None:
    """Register built-in providers. Called once at app startup."""
    if PROVIDERS:
        return
    from . import llm as llm_provider, wordnet as wordnet_provider

    register("wordnet", wordnet_provider.lookup, supports=wordnet_provider.supports)
    register("llm", llm_provider.lookup, supports=llm_provider.supports)